name: adore-cuda
channels:
  - conda-forge
channel_priority: strict
dependencies:
  - python=3.12
  - pip
  - setuptools>=80
  - wheel
  - cython
  - numpy<2
  - pandas
  - matplotlib-base
  - scipy
  - scikit-learn
  - joblib
  - networkx
  - pytz
  - tqdm
  - smt
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu124
      - torch==2.4.1+cu124
      - torch-geometric==2.6.1
      - assign_enc @ git+https://github.com/jbussemaker/AssignmentEncoding#egg=assign_enc
      - sb_arch_opt[arch_sbo,rocket]
      - open_turb_arch @ git+https://github.com/jbussemaker/OpenTurbofanArchitecting@pymoo_optional#egg=open_turb_arch
      - ./adore-2.0.0-py3-none-any.whl
      - -e .
